# GitLab CI/CD Pipeline for HomyGo - Ultra Simple
image: alpine:3.18

stages:
  - test

variables:
  GIT_DEPTH: 1

test_job:
  stage: test
  script:
    - echo "Testing HomyGo repository"
    - echo "Repository is healthy"
    - echo "Ready for deployment"
  only:
    - main
