# HomyGO Laravel Application - Fixed Configuration for Render
services:
  - type: web
    name: HomyGO-2025
    repo: https://github.com/Homygo25/HomyGO-2025
    plan: free
    region: oregon
    runtime: docker
    
    # Use Docker deployment for consistency
    dockerfilePath: ./Dockerfile.direct
    dockerContext: .
    
    # Environment variables for production
    envVars:
      - key: APP_NAME
        value: HomyGo
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://homygo.info
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
      - key: CACHE_DRIVER
        value: array
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: QUEUE_CONNECTION
        value: sync
      - key: PORT
        value: 10000
      # Database configuration (PostgreSQL)
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: homygo-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: homygo-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: homygo-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: homygo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: homygo-db
          property: password

# PostgreSQL Database
databases:
  - name: homygo-db
    databaseName: homygo
    user: homygo_user
    plan: free
    region: oregon