# Exported from Render on 2025-08-08T23:50:47Z
services:
- type: web
  name: HomyGO-2025
  runtime: docker
  repo: https://github.com/Homygo25/HomyGO-2025
  plan: free
  envVars:
  - key: APP_DEBUG
    sync: false
  - key: APP_KEY
    sync: false
  - key: QUEUE_CONNECTION
    sync: false
  - key: SESSION_LIFETIME
    sync: false
  - key: SESSION_DRIVER
    sync: false
  - key: CACHE_DRIVER
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_USERNAME
    sync: false
  - key: DB_DATABASE
    sync: false
  - key: DB_PORT
    sync: false
  - key: DB_HOST
    sync: false
  - key: DB_CONNECTION
    sync: false
  - key: LOG_LEVEL
    sync: false
  - key: LOG_CHANNEL
    sync: false
  - key: APP_URL
    sync: false
  - key: APP_ENV
    sync: false
  - key: APP_NAME
    sync: false
  - key: PORT
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile.direct
  domains:
  - homygo.info
  - www.homygo.info
  autoDeployTrigger: commit
version: "1"
