# HomyGO Laravel Application - Simplified Configuration for Render
services:
- type: web
  name: HomyGO-2025
  repo: https://github.com/Homygo25/HomyGO-2025
  plan: free
  region: oregon
  buildCommand: |
    # Install dependencies
    composer install --no-dev --optimize-autoloader --no-interaction
    npm ci
    npm run build
    
    # Setup storage directories
    mkdir -p storage/framework/{cache,sessions,views}
    mkdir -p storage/logs
    mkdir -p bootstrap/cache
    
    # Set permissions
    chmod -R 775 storage
    chmod -R 775 bootstrap/cache
    
    # Database setup
    php artisan migrate --force --no-interaction
    
  startCommand: php artisan serve --host=0.0.0.0 --port=$PORT --no-reload
    echo "Current directory: $(pwd)"
    echo "Directory contents:"
    ls -la
    echo "Database directory:"
    ls -la database/ || echo "Database directory not found"
    
    # Ensure database exists in the correct location
    mkdir -p database
    touch database/database.sqlite
    chmod 666 database/database.sqlite
    
    # Verify database file exists
    echo "Database file status:"
    ls -la database/database.sqlite
    
    # Run migrations and seed at startup
    php artisan migrate --force --no-interaction
    php artisan db:seed --class=RoleSeeder --force --no-interaction
    
    # Cache configs for performance (skip if errors occur)
    php artisan config:cache || echo "Config cache skipped"
    php artisan route:cache || echo "Route cache skipped"
    php artisan view:cache || echo "View cache skipped"
    
    # Create storage link
    php artisan storage:link --force || echo "Storage link skipped"
    
    # Start server bound to 0.0.0.0 with PORT from environment
    echo "Starting server on 0.0.0.0:${PORT}"
    php artisan serve --host=0.0.0.0 --port=${PORT}
  autoDeployTrigger: commit
  envVars:
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: false
  - key: APP_KEY
    generateValue: true
  - key: APP_URL
    fromService:
      type: web
      name: HomyGO-2025
      property: host
  - key: DB_CONNECTION
    value: sqlite
  - key: DB_DATABASE
    value: /var/www/html/database/database.sqlite
  - key: LOG_CHANNEL
    value: stderr
  - key: LOG_LEVEL
    value: error
  - key: SESSION_DRIVER
    value: database
  - key: CACHE_STORE
    value: database
  - key: QUEUE_CONNECTION
    value: database
  - key: MAIL_MAILER
    value: log
  - key: MAIL_FROM_ADDRESS
    value: noreply@homygo.com
  - key: MAIL_FROM_NAME
    value: HomyGO
  - key: APP_NAME
    value: HomyGO
  - key: APP_LOCALE
    value: en
  - key: APP_FALLBACK_LOCALE
    value: en
  - key: BCRYPT_ROUNDS
    value: 12
  - key: SESSION_LIFETIME
    value: 120
  - key: SESSION_PATH
    value: /
  - key: SESSION_ENCRYPT
    value: false
version: "1"
